# Generated by Django 4.1.9 on 2023-05-15 01:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("health", "0002_alter_appointment_therapist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="suggestion",
            name="is_specific_to_age_group",
        ),
        migrations.RemoveField(
            model_name="suggestion",
            name="is_specific_to_gender",
        ),
    ]
