# Generated by Django 4.1.9 on 2023-05-15 01:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("health", "0003_remove_suggestion_is_specific_to_age_group_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mood",
            name="description",
        ),
        migrations.AddField(
            model_name="suggestion",
            name="from_age",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="suggestion",
            name="to_age",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
