# Generated by Django 4.1.9 on 2023-05-15 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_user_is_therapist_therapist"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("health", "0004_remove_mood_description_suggestion_from_age_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rating", models.IntegerField()),
                ("comment", models.TextField()),
                (
                    "therapist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="feedbacks", to="users.therapist"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="message",
            name="relative",
        ),
        migrations.AddField(
            model_name="appointment",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="therapist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="appointments", to="users.therapist"
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="appointments", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="Therapist",
        ),
    ]
