# Generated by Django 4.1.9 on 2023-05-15 14:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("health", "0005_feedback_remove_message_relative_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Feedback",
        ),
    ]
