# Generated by Django 4.1.9 on 2023-05-16 01:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("health", "0007_sendmail_remove_suggestion_from_age_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "Admin Message", "verbose_name_plural": "Admin Messages"},
        ),
    ]
