# Generated by Django 4.1.9 on 2023-05-16 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("health", "0008_alter_message_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SendMail",
        ),
        migrations.AlterModelOptions(
            name="appointment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Admin Message",
                "verbose_name_plural": "Admin Messages",
            },
        ),
        migrations.AlterModelOptions(
            name="mood",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="suggestion",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="appointment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="message",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mood",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="relative",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="suggestion",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
