# Generated by Django 4.1.9 on 2023-05-16 15:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("health", "0009_delete_sendmail_alter_appointment_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Appointment",
        ),
    ]
