# Generated by Django 4.1.9 on 2023-05-14 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("health", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="brain_health_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_therapist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="preferred_therapist",
                to="health.therapist",
            ),
        ),
    ]
