# Generated by Django 4.1.9 on 2023-05-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_brain_health_score_user_preferred_therapist"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(default=11, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(default="asd", upload_to="user_profiles/"),
            preserve_default=False,
        ),
    ]
