# Generated by Django 4.1.9 on 2023-05-15 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_remove_user_preferred_therapist"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_therapist",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Therapist",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phone_number", models.CharField(max_length=20)),
                ("profile_picture", models.ImageField(upload_to="therapist_profiles/")),
                ("degrees", models.TextField()),
                ("certifications", models.TextField()),
                ("hourly_rate", models.DecimalField(decimal_places=2, max_digits=6)),
                ("is_available", models.BooleanField(default=False)),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="therapist_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
