# Generated by Django 4.1.9 on 2023-05-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_remove_therapist_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="therapist",
            name="certifications",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="therapist",
            name="degrees",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="therapist",
            name="hourly_rate",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
