# Generated by Django 4.1.9 on 2023-05-16 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_alter_user_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="brain_health_score",
        ),
        migrations.CreateModel(
            name="Brain_Health_Score",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rating", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Brain_Score",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
