# Generated by Django 4.1.9 on 2023-05-16 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_remove_user_brain_health_score_brain_health_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brain_health_score",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="brain_score", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
