# Generated by Django 4.1.9 on 2023-05-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_alter_brain_health_score_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Send_To_Relative",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Send To Relative",
                "verbose_name_plural": "Send To Relatives",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Suggestion_Therapist",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Suggestion Therapist",
                "verbose_name_plural": "Suggestion Therapists",
                "ordering": ["-created_at"],
            },
        ),
    ]
