# Generated by Django 4.1.9 on 2023-05-16 14:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_send_to_relative_suggestion_therapist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="therapist",
            name="is_approved",
        ),
    ]
