# Generated by Django 4.1.9 on 2023-05-17 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_alter_feedback_therapist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="therapist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointment_User",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
