# Generated by Django 4.1.9 on 2023-05-17 15:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0021_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="appointment",
            field=models.OneToOneField(
                default=0, on_delete=django.db.models.deletion.CASCADE, related_name="review", to="users.appointment"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="brain_health_score",
            name="rating",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="rating",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]
            ),
        ),
        migrations.CreateModel(
            name="UserHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "appointment",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="users.appointment"),
                ),
                (
                    "therapist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="therapist_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
