# Generated by Django 4.1.9 on 2023-05-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0022_feedback_appointment_alter_brain_health_score_rating_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="is_confirmed",
        ),
        migrations.AddField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("BOOKED", "Booked"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("CANCELED", "Canceled"),
                ],
                default="BOOKED",
                max_length=20,
            ),
        ),
    ]
